### ISSUE TITLE
Add support for authorization flow

### ISSUE THREAD

**Issue by justasm** [pakerfeldt/okhttp-signpost#9]
This wrapper fulfills the first purpose of Signpost -- signing HTTP messages -- but not the second -- requesting tokens from the OAuth service provider.

Would it be appropriate to add support for the authorization flow (i.e. via an `OkHttpOAuthProvider` and `OkHttpResponseAdapter`), or is this outside the scope of this extension?

**Comment by pakerfeldt** [comment]
It's definitely within scope. I just haven't come around doing it yet. I'm happy to receive a PR if you want to pursue that.
